function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("handler#menu", "load")
end

function on_message(self, message_id, message,sender)
	if message_id == hash("proxy_loaded")then	
		msg.post(sender, "enable")	
		--print("loaded")
	elseif message_id == hash("show_game") then
		msg.post("handler#game", "load")
		-- msg.post("handler#menu", "unload")
		local cameraGO = go.set("/camera", "position", vmath.vector3(320,1136*.5,0))
		print(cameraGO)
	end
end